"""add deep research summary to arxiv entries

Revision ID: 243431fd3fe3
Revises: 81ff26aff3e6
Create Date: 2026-06-14 03:42:45.421447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243431fd3fe3'
down_revision: Union[str, Sequence[str], None] = '81ff26aff3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arxiv_entries', sa.Column('deep_research_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arxiv_entries', 'deep_research_summary')
    # ### end Alembic commands ###
