"""drop query_hash columns

Revision ID: 5f9dd6019831
Revises: 243431fd3fe3
Create Date: 2026-06-18 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9dd6019831'
down_revision: Union[str, Sequence[str], None] = '243431fd3fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_digest_date_query'), 'digests', type_='unique')
    op.drop_index(op.f('ix_digests_query_hash'), table_name='digests')
    op.drop_column('digests', 'query_hash')
    op.drop_column('external_query_states', 'query_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_query_states', sa.Column('query_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('digests', sa.Column('query_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_digests_query_hash'), 'digests', ['query_hash'], unique=False)
    op.create_unique_constraint(op.f('uq_digest_date_query'), 'digests', ['digest_date', 'query_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
