"""create arxiv_entries table

Revision ID: 618c7ea43c41
Revises: 
Create Date: 2026-06-05 18:08:12.819530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618c7ea43c41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arxiv_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arxiv_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('categories', sa.Text(), nullable=False),
    sa.Column('published', sa.DateTime(timezone=True), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arxiv_entries_arxiv_id'), 'arxiv_entries', ['arxiv_id'], unique=True)
    op.create_index(op.f('ix_arxiv_entries_published'), 'arxiv_entries', ['published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arxiv_entries_published'), table_name='arxiv_entries')
    op.drop_index(op.f('ix_arxiv_entries_arxiv_id'), table_name='arxiv_entries')
    op.drop_table('arxiv_entries')
    # ### end Alembic commands ###
