"""create digests table

Revision ID: 81ff26aff3e6
Revises: 0ac136afaf46
Create Date: 2026-06-14 01:53:54.888745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '81ff26aff3e6'
down_revision: Union[str, Sequence[str], None] = '0ac136afaf46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('query_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_entry_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest_date', 'query_hash', name='uq_digest_date_query')
    )
    op.create_index(op.f('ix_digests_digest_date'), 'digests', ['digest_date'], unique=False)
    op.create_index(op.f('ix_digests_query_hash'), 'digests', ['query_hash'], unique=False)
    op.alter_column('external_query_states', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_external_query_states_source_query'), table_name='external_query_states')
    op.drop_constraint(op.f('uq_source_query_hash'), 'external_query_states', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_source_query_hash'), 'external_query_states', ['source', 'query_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_external_query_states_source_query'), 'external_query_states', ['source', 'query_hash'], unique=False)
    op.alter_column('external_query_states', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_digests_query_hash'), table_name='digests')
    op.drop_index(op.f('ix_digests_digest_date'), table_name='digests')
    op.drop_table('digests')
    # ### end Alembic commands ###
