"""add query columns

Revision ID: c7a7d0a6e4b8
Revises: 5f9dd6019831
Create Date: 2026-06-18 00:00:01.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a7d0a6e4b8'
down_revision: Union[str, Sequence[str], None] = '5f9dd6019831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column('query', sa.String(length=255), server_default='', nullable=False))
    op.create_index(op.f('ix_digests_query'), 'digests', ['query'], unique=False)
    op.create_unique_constraint(op.f('uq_digest_date_query'), 'digests', ['digest_date', 'query'], postgresql_nulls_not_distinct=False)
    op.alter_column('digests', 'query', server_default=None)
    op.add_column('external_query_states', sa.Column('query', sa.String(length=255), server_default='', nullable=False))
    op.alter_column('external_query_states', 'query', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_query_states', 'query')
    op.drop_constraint(op.f('uq_digest_date_query'), 'digests', type_='unique')
    op.drop_index(op.f('ix_digests_query'), table_name='digests')
    op.drop_column('digests', 'query')
    # ### end Alembic commands ###
